name: Latest Dev.to post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs once a day at midnight
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest Dev.to posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: 'https://dev.to/feed/oeharuki'
          template: '$newline- $date [$title]($url)'
          date_format: 'yyyy-mm-dd'
          comment_tag_name: 'DEV-TO-POST-LIST'
